apiVersion: v1
kind: PersistentVolume
metadata:
  name: stocks-pv
  namespace: multi-service-app 
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"


