apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  selector:
    app: database-app
  type: NodePort 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080