apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocks
  namespace: multi-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stocks
  template:
    metadata:
      labels:
        app: stocks
    spec:
      containers:
        - name: stocks
          image: stocks:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: COLLECTION_NAME
              value: stocks1