apiVersion: v1
kind: Service
metadata:
  name: stocks-service
  namespace: multi-service-app
spec:
  selector:
    app: stocks
  type: ClusterIP 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      # nodePort: 30082