apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraPortMappings:
        # Expose only the nginx service on the host to external traffic 
      - containerPort: 31322 # NodePort of the nginx service
        hostPort: 80 # Port on the host
    