services: 
  mongodb:
    image: mongo
    ports: 
      - "27017:27017"
    volumes:
      - /data/db
    # restart: always
  stocks1-a:
    build: ./stocks
    ports: 
      - "5001:8000" #Host Port:Container Port
    expose:
      - "8000"
    environment:
      - COLLECTION_NAME=stocks1
    depends_on:
      - mongodb
    volumes:
      - /app/data
    restart: always
  stocks1-b:
    build: ./stocks
    ports: 
      - "5004:8000"
    expose:
      - "8000"
    environment:
      - COLLECTION_NAME=stocks1
    depends_on:
      - mongodb
    volumes:
      - /app/data
    restart: always
  stocks2:
    build: ./stocks
    ports: 
      - "5002:8000"
    expose:
      - "8000"
    environment:
      - COLLECTION_NAME=stocks2
    depends_on:
      - mongodb
    volumes:
      - /app/data
    restart: always
  capital-gains:
    build: ./capital-gains
    ports: 
      - "5003:8080"
    expose:
      - "8080"
    depends_on:
      - stocks1-a
      - stocks1-b
      - stocks2
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    depends_on:
      - stocks1-a
      - stocks1-b
      - stocks2