apiVersion: v1
kind: Service
metadata:
  name: capital-gains-service
  namespace: multi-service-app
spec:
  selector:
    app: capital-gains
  type: ClusterIP 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      # nodePort: 30081