apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30082 # NodePort of the stocks service
        hostPort: 8000
      - containerPort: 30081 # NodePort of the capital-gains service
        hostPort: 8080
      - containerPort: 30080 # NodePort of the database service
        hostPort: 5000     
      - containerPort: 31322 # NodePort of the nginx service
        hostPort: 80
    