apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: multi-service-app
data:
  nginx.conf: |
    events {}

    http {
    # do a weighted round robin between each stock
      upstream stocks-service {
        server stocks-service.multi-service-app.svc.cluster.local:8000;
      }

      upstream capital_gains_service {
        server capital-gains-service.multi-service-app.svc.cluster.local:8080;
      }

      server {
        listen 80;
        location /stocks {
          proxy_pass http://stocks-service;
        }
        location /capital-gains {
          proxy_pass http://capital_gains_service;
        }
      }
    }


